server:
  port: 8900 #端口号
############################################# Spring Cloud Ribbon 负载均衡配置##########################
eureka:
  client:
    register-with-eureka: false #本微服务为服务消费者，不需要将自己注册到服务注册中心
    fetch-registry: true  #本微服务为服务消费者，需要到服务注册中心搜索服务
    service-url:
      defaultZone: http://eureka8610.com:8610/eureka/,http://eureka8611.com:8611/eureka/,http://eureka8612.com:8612/eureka/ #服务注册中心集群